version: 0.0
os: linux
files:
  - source: /
    # destination: /usr/share/nginx/html
    destination: /var/www/zignaly-affiliates/
    overwrite: true
# hooks:
#   BeforeInstall:
#     - location: scripts/BeforeInstallHook.sh
#       timeout: 300
#   AfterInstall:
#     - location: scripts/AfterInstallHook.sh
#       timeout: 300
