export const USER_AFFILIATE = 'AFFILIATE';
export const USER_MERCHANT = 'MERCHANT';

export const SERVICE_TYPE_MONTHLY_FEE = 'MONTHLY_FEE';
export const SERVICE_TYPE_PROFIT_SHARING = 'PROFIT_SHARING';

export const SERVICE_BASE = 'https://zignaly.com/';

export const DISCOUNT_CODE_EXTRA_LIFE = 'EXTRA_LIFE';
export const DISCOUNT_CODE_PERCENT = 'PERCENT';
export const DISCOUNT_CODE_FIXED_AMOUNT = 'FIXED_AMOUNT';

export const REWARD_DURATION = 'DURATION';
export const REWARD_PERCENT = 'PERCENT';
export const REWARD_FIXED_AMOUNT = 'FIXED_AMOUNT';
