export const PAYOUT_STATUSES = {
  NOT_ENOUGH: 'NOT_ENOUGH',
  ENOUGH_BUT_NO_PAYOUT: 'ENOUGH_BUT_NO_PAYOUT',
  CAN_CHECKOUT: 'CAN_CHECKOUT',
  REJECTED: 'REJECTED',
  REQUESTED: 'REQUESTED',
  PAID: 'PAID',
};

export const CONVERSION_STATUSES = {
  COMPLETE: 'COMPLETE',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
};
